### PR TITLE
Include db statistics in engine status

### PR DESCRIPTION
**Pull request by IslamAbdelRahman**
Add DB Statistics to "SHOW ENGINE ROCKSDB STATUS"

output looks like this P57244900

### CODE REVIEW

**Review by alxyang — APPROVED** [review]
lgtm. will land once i confirm tests pass

**Review by alxyang — CHANGES_REQUESTED** [review]
rocksdb.show_engine needs to be rerecorded

**Comment by IslamAbdelRahman** [comment]
@alxyang, can you please explain what do you mean by rerecording rocksdb.show_engine

**Comment by reidHoruff** [comment]
Run the test but supply the --record flag so output is re-recorded

eg:

../tools/mysqltest.sh rocksdb.show_engine --record

**Comment by IslamAbdelRahman** [comment]
Thanks @reidHoruff, I updated the PR

**Review by alxyang — APPROVED** [review]

**Pull request closed without merging**
