### PR TITLE
Add table factory options to information_schema

### PR DESCRIPTION
**Pull request by vrofze**
- Add `TABLE_FACTORY_NAME` to table `information_schema.ROCKSDB_CF_OPTIONS`
- Add table `ROCKSDB_TF_OPTIONS` to information_schema, while the table shows table factory options(add function `split_into_vector` for split options with order)

### CODE REVIEW

**Comment by reidHoruff** [comment]
Anyone know why this can't be imported to phabricator?

**Comment by vrofze** [comment]
Sorry, i didn't sign up at cla before, is that the reason?

**Comment by reidHoruff** [comment]
You'll need to re-record test rocksdb.show_engine, main.mysqlshow, and main.mysqld--help-notwin.  EDIT: and main.mysqld--help-notwin-profiling

**Comment by reidHoruff** [comment]
Also, please add a simple test querying the information schema added.

**Comment by hermanlee** [comment]
I imported and re-implemented the functionality in the existing information_schema.rocksdb_cf_options table:
 
https://github.com/facebook/mysql-5.6/commit/02eaa286fd320827f6be631fd73ba8b61d6a1287

If this is not sufficient, we can revisit this pull request.

**Pull request closed without merging**
