### PR TITLE
FB8-240: merge_small_tests fails in RelWithDebInfo after introducing high priority DDLs

### PR DESCRIPTION
**Pull request by inikep**
https://jira.percona.com/browse/FB8-240

Fix RelWithDebInfo compilation after introducing high priority DDLs at https://github.com/facebook/mysql-5.6/commit/2924b1fb01f6 by using dummy implementations of some functions.

### CODE REVIEW

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Comment by hermanlee** [comment]
Already merged in.

**Comment by inikep** [comment]
It's merged into `fb-mysql-8.0.17`, but still fails with `fb-mysql-8.0.13`.

**Comment by hermanlee** [comment]
We've moved all development to 8.0.17. Do you still need this for 8.0.13 development for dependency replication?

**Comment by inikep** [comment]
No problem, I can manage without it.

**Pull request closed without merging**
