### PR TITLE
- Normalize rocksdb_sysvars include files, moving rocksdb_sys_var.inc…

### PR DESCRIPTION
**Pull request by george-lorch**
… and

  correctboolvalue.inc from suite/sys_vars/inc to
  suite/rocksdb_sys_vars/include. This is inline with other suites and engines.
- Fixed up all tests touching to use the new locations.
- Makes it easier for downstream to detect changes to files that fall outside
  of the rocksdb* suites.

### CODE REVIEW

**Review by alxyang — APPROVED** [review]
thanks for your contribution!

**Comment by alxyang** [comment]
hey @georgelorchpercona we had some issues internally with our open source tooling that was preventing me from landing your change until now.

Can you rebase on top of fb-mysql-5.6.35 branch and fix the conflicts? Thanks :)

**Comment by hermanlee** [comment]
I rebased and pushed the change.

**Comment by george-lorch** [comment]
Ohhh, sorry about that guys, I started to rebase, then must have seen something shiny and completely forgot about it.

**Pull request closed without merging**
