### PR TITLE
FB8-242: Force minimal required version of liblz4 (1.8.0) and libzstd (1.4.0)

### PR DESCRIPTION
**Pull request by inikep**
Summary:
https://github.com/facebook/mysql-5.6/commit/3339788feb5 introduced changes that require newer versions of liblz4 (1.8.0) and libzstd (1.4.0).
This causes compilation errors with older libs e.g. for Ubuntu Bionic which has liblz4-dev 1.7.1 and libzstd-dev 1.3.3.
More information at https://jira.percona.com/browse/FB8-242

This patch solves the issues with the following changes:
1. Check minimal required version of liblz4 (1.8.0) and libzstd (1.4.0)
2. Add bundled liblz4 to 1.8.0
3. Add bundled libzstd 1.4.0

Originally Reviewed By: lth

### CODE REVIEW

**Comment by percona-ysorokin** [comment]
Patch already imported to fb-mysql-8.0.17
https://github.com/facebook/mysql-5.6/commit/e7385e70149
This PR should be closed.

**Comment by inikep** [comment]
@percona-ysorokin This is patch for `fb-mysql-5.6.35`. I had the same compilation issues as with `fb-mysql-8.0.17` on Ubuntu Bionic. Sometimes 5.6 is helpful to test some feature that I'm porting to 8.0.

**Comment by percona-ysorokin** [comment]
@hermanlee Sorry for the confusion, I did not notice that this PR is intended for 5.6.35. Therefore, it should not be closed.

**Comment by inikep** [comment]
Partially fixed with https://github.com/facebook/mysql-5.6/commit/7e0b60e2955e2de42f32fe1494a446eb16b61780

**Pull request closed without merging**
