### PR TITLE
FB8-96: Remove special formatting for user name when writing to audit plugin log

### PR DESCRIPTION
**Pull request by dutow**
Jira issue: https://jira.percona.com/browse/FB8-96

Reference patch: https://github.com/facebook/mysql-5.6/commit/3b47dae
Reference patch: https://github.com/facebook/mysql-5.6/commit/87e0683

### CODE REVIEW

**Review by percona-ysorokin — APPROVED** [review]
LGTM

**Comment by percona-ysorokin** [comment]
The PR title should be FB8-96

**Review by hermanlee — APPROVED** [review]

**Review by hermanlee — CHANGES_REQUESTED** [review]
Looks like this doesn't build with a reference to make_user_name in log.cc.

```
/trunk-git-mysql/sql/log.cc: In member function ‘bool Query_logger::general_log_write(THD*, enum_server_command, const char*, size_t)’:
/trunk-git-mysql/sql/log.cc:1414:61: error: ‘make_user_name’ was not declared in this scope
       make_user_name(thd->security_context(), user_host_buff);
```

**Comment by dutow** [comment]
Ops, that file shouldn't have been part of the diff, fixed it.

**Review by hermanlee — APPROVED** [review]

**Pull request closed without merging**
