### PR TITLE
Run clang-format on storage/rocksdb

### PR DESCRIPTION
**Pull request by laurynas-biveinis**
Since it touched one of the lines with these debugging sync points, use this opportunity to fix "stimulate/simulate" typo too.

### CODE REVIEW

**Comment by laurynas-biveinis** [comment]
It is less than ideal to make a formatting-only PR, but tools complained all the time and
```
  void remove_from_global_trx_list(void) {
    DBUG_EXECUTE_IF("rocksdb_trx_list_crash", {
      if (!m_thd->is_system_thread() &&
          !m_thd->is_attachable_transaction_active()) {
        THD *thd = new THD();
      thd->thread_stack = reinterpret_cast<char *>(&(thd));
```
crossed the threshold for me

**Comment by luqun** [comment]
I had thought we had done this before. let's test it in CI

**Comment by laurynas-biveinis** [comment]
This is clang-format 16. Let me know if you are using a different version

**Comment by luqun** [comment]
> This is clang-format 16. Let me know if you are using a different version

we use an old version and it doesn't complain your change. so we should be good to go.

**Pull request closed without merging**
